spring:
  kafka:
    template:
      observation-enabled: true # set kafka producer headers

management:
  tracing:
    propagation:
      type: w3c
    enabled: true
    sampling:
      probability: 1.0 # report 100% of traces
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_GRPC_BASE_URL:http://localhost:4317}
          transport: grpc
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_HTTP_BASE_URL:http://localhost:4318}/v1/metrics
        step: 30s
