application:
  gateway:
    excluded-services:
      - consul
      - gate
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: config
              uri: lb://config
              predicates:
                - Path=/config/**
              filters:
                - StripPrefix=1
                - AddHighLog
                - AddLogging
                - TfaTokenDetection
                - AccessControl
                - AddDomainRelayHeaders
                - IdpStatefulMode
                - name: RateLimitByTenantKey
                  args:
                    capacity: 10
                    period: 1 # in_minutes
                - name: RateLimitByClientKey
                  args:
                    capacity: 5
                    period: 1 # in_minutes
            - id: entity
              uri: lb://entity
              predicates:
                - Path=/entity/**
              filters:
                - StripPrefix=1
                - AddHighLog
                - AddLogging
                - AccessControl
                - AddDomainRelayHeaders
            - id: uaa
              uri: lb://uaa
              predicates:
                - Path=/uaa/**
              filters:
                - StripPrefix=1
                - AddHighLog
                - AddLogging
                - AccessControl
                - AddDomainRelayHeaders
