application:
  gateway:
    excluded-services:
      - consul
      - gate
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: config
              uri: lb://config
              predicates:
                - Path=/config/**
              filters:
                - StripPrefix=1
                - AddHighLog
                - AddLogging
                - TfaTokenDetection
                - AddDomainRelayHeaders
                - IdpStatefulMode
            - id: entity
              uri: lb://entity
              predicates:
                - Path=/entity/**
              filters:
                - StripPrefix=1
                - AddHighLog
                - AddLogging
                - AddDomainRelayHeaders
            - id: uaa
              uri: lb://uaa
              predicates:
                - Path=/uaa/**
              filters:
                - StripPrefix=1
                - AddHighLog
                - AddLogging
                - AddDomainRelayHeaders
