// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: home/ssenko/work/xm-gate/src/main/resources/config/proto/OAuth2AuthorizationRequest.proto

package com.icthh.xm.gate.security.oauth2.dto;

public final class OAuth2AuthorizationRequest {
  private OAuth2AuthorizationRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OAuth2AuthorizationRequestDtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequestDto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string authorizationUri = 1;</code>
     * @return The authorizationUri.
     */
    java.lang.String getAuthorizationUri();
    /**
     * <code>string authorizationUri = 1;</code>
     * @return The bytes for authorizationUri.
     */
    com.google.protobuf.ByteString
        getAuthorizationUriBytes();

    /**
     * <code>string clientId = 2;</code>
     * @return The clientId.
     */
    java.lang.String getClientId();
    /**
     * <code>string clientId = 2;</code>
     * @return The bytes for clientId.
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>string redirectUri = 3;</code>
     * @return The redirectUri.
     */
    java.lang.String getRedirectUri();
    /**
     * <code>string redirectUri = 3;</code>
     * @return The bytes for redirectUri.
     */
    com.google.protobuf.ByteString
        getRedirectUriBytes();

    /**
     * <code>repeated string scopes = 4;</code>
     * @return A list containing the scopes.
     */
    java.util.List<java.lang.String>
        getScopesList();
    /**
     * <code>repeated string scopes = 4;</code>
     * @return The count of scopes.
     */
    int getScopesCount();
    /**
     * <code>repeated string scopes = 4;</code>
     * @param index The index of the element to return.
     * @return The scopes at the given index.
     */
    java.lang.String getScopes(int index);
    /**
     * <code>repeated string scopes = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the scopes at the given index.
     */
    com.google.protobuf.ByteString
        getScopesBytes(int index);

    /**
     * <code>string state = 5;</code>
     * @return The state.
     */
    java.lang.String getState();
    /**
     * <code>string state = 5;</code>
     * @return The bytes for state.
     */
    com.google.protobuf.ByteString
        getStateBytes();

    /**
     * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
     */
    int getAdditionalParametersCount();
    /**
     * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
     */
    boolean containsAdditionalParameters(
        java.lang.String key);
    /**
     * Use {@link #getAdditionalParametersMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAdditionalParameters();
    /**
     * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAdditionalParametersMap();
    /**
     * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
     */

    java.lang.String getAdditionalParametersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
     */

    java.lang.String getAdditionalParametersOrThrow(
        java.lang.String key);

    /**
     * <code>string authorizationRequestUri = 7;</code>
     * @return The authorizationRequestUri.
     */
    java.lang.String getAuthorizationRequestUri();
    /**
     * <code>string authorizationRequestUri = 7;</code>
     * @return The bytes for authorizationRequestUri.
     */
    com.google.protobuf.ByteString
        getAuthorizationRequestUriBytes();

    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    int getAttributesCount();
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    boolean containsAttributes(
        java.lang.String key);
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAttributes();
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAttributesMap();
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */

    java.lang.String getAttributesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */

    java.lang.String getAttributesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequestDto}
   */
  public static final class OAuth2AuthorizationRequestDto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequestDto)
      OAuth2AuthorizationRequestDtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OAuth2AuthorizationRequestDto.newBuilder() to construct.
    private OAuth2AuthorizationRequestDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OAuth2AuthorizationRequestDto() {
      authorizationUri_ = "";
      clientId_ = "";
      redirectUri_ = "";
      scopes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      state_ = "";
      authorizationRequestUri_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OAuth2AuthorizationRequestDto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OAuth2AuthorizationRequestDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              authorizationUri_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              redirectUri_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                scopes_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              scopes_.add(s);
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              state_ = s;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                additionalParameters_ = com.google.protobuf.MapField.newMapField(
                    AdditionalParametersDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              additionalParameters__ = input.readMessage(
                  AdditionalParametersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              additionalParameters_.getMutableMap().put(
                  additionalParameters__.getKey(), additionalParameters__.getValue());
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              authorizationRequestUri_ = s;
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                attributes_ = com.google.protobuf.MapField.newMapField(
                    AttributesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              attributes__ = input.readMessage(
                  AttributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              attributes_.getMutableMap().put(
                  attributes__.getKey(), attributes__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          scopes_ = scopes_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetAdditionalParameters();
        case 8:
          return internalGetAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto.class, com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto.Builder.class);
    }

    public static final int AUTHORIZATIONURI_FIELD_NUMBER = 1;
    private volatile java.lang.Object authorizationUri_;
    /**
     * <code>string authorizationUri = 1;</code>
     * @return The authorizationUri.
     */
    @java.lang.Override
    public java.lang.String getAuthorizationUri() {
      java.lang.Object ref = authorizationUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authorizationUri_ = s;
        return s;
      }
    }
    /**
     * <code>string authorizationUri = 1;</code>
     * @return The bytes for authorizationUri.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorizationUriBytes() {
      java.lang.Object ref = authorizationUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authorizationUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object clientId_;
    /**
     * <code>string clientId = 2;</code>
     * @return The clientId.
     */
    @java.lang.Override
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>string clientId = 2;</code>
     * @return The bytes for clientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REDIRECTURI_FIELD_NUMBER = 3;
    private volatile java.lang.Object redirectUri_;
    /**
     * <code>string redirectUri = 3;</code>
     * @return The redirectUri.
     */
    @java.lang.Override
    public java.lang.String getRedirectUri() {
      java.lang.Object ref = redirectUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        redirectUri_ = s;
        return s;
      }
    }
    /**
     * <code>string redirectUri = 3;</code>
     * @return The bytes for redirectUri.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRedirectUriBytes() {
      java.lang.Object ref = redirectUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        redirectUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCOPES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList scopes_;
    /**
     * <code>repeated string scopes = 4;</code>
     * @return A list containing the scopes.
     */
    public com.google.protobuf.ProtocolStringList
        getScopesList() {
      return scopes_;
    }
    /**
     * <code>repeated string scopes = 4;</code>
     * @return The count of scopes.
     */
    public int getScopesCount() {
      return scopes_.size();
    }
    /**
     * <code>repeated string scopes = 4;</code>
     * @param index The index of the element to return.
     * @return The scopes at the given index.
     */
    public java.lang.String getScopes(int index) {
      return scopes_.get(index);
    }
    /**
     * <code>repeated string scopes = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the scopes at the given index.
     */
    public com.google.protobuf.ByteString
        getScopesBytes(int index) {
      return scopes_.getByteString(index);
    }

    public static final int STATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object state_;
    /**
     * <code>string state = 5;</code>
     * @return The state.
     */
    @java.lang.Override
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state_ = s;
        return s;
      }
    }
    /**
     * <code>string state = 5;</code>
     * @return The bytes for state.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDITIONALPARAMETERS_FIELD_NUMBER = 6;
    private static final class AdditionalParametersDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_AdditionalParametersEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> additionalParameters_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAdditionalParameters() {
      if (additionalParameters_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AdditionalParametersDefaultEntryHolder.defaultEntry);
      }
      return additionalParameters_;
    }

    public int getAdditionalParametersCount() {
      return internalGetAdditionalParameters().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
     */

    @java.lang.Override
    public boolean containsAdditionalParameters(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAdditionalParameters().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAdditionalParametersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAdditionalParameters() {
      return getAdditionalParametersMap();
    }
    /**
     * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getAdditionalParametersMap() {
      return internalGetAdditionalParameters().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
     */
    @java.lang.Override

    public java.lang.String getAdditionalParametersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAdditionalParameters().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
     */
    @java.lang.Override

    public java.lang.String getAdditionalParametersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAdditionalParameters().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int AUTHORIZATIONREQUESTURI_FIELD_NUMBER = 7;
    private volatile java.lang.Object authorizationRequestUri_;
    /**
     * <code>string authorizationRequestUri = 7;</code>
     * @return The authorizationRequestUri.
     */
    @java.lang.Override
    public java.lang.String getAuthorizationRequestUri() {
      java.lang.Object ref = authorizationRequestUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authorizationRequestUri_ = s;
        return s;
      }
    }
    /**
     * <code>string authorizationRequestUri = 7;</code>
     * @return The bytes for authorizationRequestUri.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorizationRequestUriBytes() {
      java.lang.Object ref = authorizationRequestUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authorizationRequestUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTRIBUTES_FIELD_NUMBER = 8;
    private static final class AttributesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_AttributesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> attributes_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAttributes() {
      if (attributes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      return attributes_;
    }

    public int getAttributesCount() {
      return internalGetAttributes().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */

    @java.lang.Override
    public boolean containsAttributes(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAttributes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
      return getAttributesMap();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
      return internalGetAttributes().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    @java.lang.Override

    public java.lang.String getAttributesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttributes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    @java.lang.Override

    public java.lang.String getAttributesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttributes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAuthorizationUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, authorizationUri_);
      }
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientId_);
      }
      if (!getRedirectUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, redirectUri_);
      }
      for (int i = 0; i < scopes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, scopes_.getRaw(i));
      }
      if (!getStateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, state_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAdditionalParameters(),
          AdditionalParametersDefaultEntryHolder.defaultEntry,
          6);
      if (!getAuthorizationRequestUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, authorizationRequestUri_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAttributes(),
          AttributesDefaultEntryHolder.defaultEntry,
          8);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAuthorizationUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, authorizationUri_);
      }
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientId_);
      }
      if (!getRedirectUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, redirectUri_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < scopes_.size(); i++) {
          dataSize += computeStringSizeNoTag(scopes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getScopesList().size();
      }
      if (!getStateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, state_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAdditionalParameters().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        additionalParameters__ = AdditionalParametersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, additionalParameters__);
      }
      if (!getAuthorizationRequestUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, authorizationRequestUri_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAttributes().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        attributes__ = AttributesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(8, attributes__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto)) {
        return super.equals(obj);
      }
      com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto other = (com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto) obj;

      if (!getAuthorizationUri()
          .equals(other.getAuthorizationUri())) return false;
      if (!getClientId()
          .equals(other.getClientId())) return false;
      if (!getRedirectUri()
          .equals(other.getRedirectUri())) return false;
      if (!getScopesList()
          .equals(other.getScopesList())) return false;
      if (!getState()
          .equals(other.getState())) return false;
      if (!internalGetAdditionalParameters().equals(
          other.internalGetAdditionalParameters())) return false;
      if (!getAuthorizationRequestUri()
          .equals(other.getAuthorizationRequestUri())) return false;
      if (!internalGetAttributes().equals(
          other.internalGetAttributes())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AUTHORIZATIONURI_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorizationUri().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + REDIRECTURI_FIELD_NUMBER;
      hash = (53 * hash) + getRedirectUri().hashCode();
      if (getScopesCount() > 0) {
        hash = (37 * hash) + SCOPES_FIELD_NUMBER;
        hash = (53 * hash) + getScopesList().hashCode();
      }
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState().hashCode();
      if (!internalGetAdditionalParameters().getMap().isEmpty()) {
        hash = (37 * hash) + ADDITIONALPARAMETERS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAdditionalParameters().hashCode();
      }
      hash = (37 * hash) + AUTHORIZATIONREQUESTURI_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorizationRequestUri().hashCode();
      if (!internalGetAttributes().getMap().isEmpty()) {
        hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAttributes().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequestDto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequestDto)
        com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetAdditionalParameters();
          case 8:
            return internalGetAttributes();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableAdditionalParameters();
          case 8:
            return internalGetMutableAttributes();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto.class, com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto.Builder.class);
      }

      // Construct using com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        authorizationUri_ = "";

        clientId_ = "";

        redirectUri_ = "";

        scopes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = "";

        internalGetMutableAdditionalParameters().clear();
        authorizationRequestUri_ = "";

        internalGetMutableAttributes().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_descriptor;
      }

      @java.lang.Override
      public com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto getDefaultInstanceForType() {
        return com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto.getDefaultInstance();
      }

      @java.lang.Override
      public com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto build() {
        com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto buildPartial() {
        com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto result = new com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto(this);
        int from_bitField0_ = bitField0_;
        result.authorizationUri_ = authorizationUri_;
        result.clientId_ = clientId_;
        result.redirectUri_ = redirectUri_;
        if (((bitField0_ & 0x00000001) != 0)) {
          scopes_ = scopes_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.scopes_ = scopes_;
        result.state_ = state_;
        result.additionalParameters_ = internalGetAdditionalParameters();
        result.additionalParameters_.makeImmutable();
        result.authorizationRequestUri_ = authorizationRequestUri_;
        result.attributes_ = internalGetAttributes();
        result.attributes_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto) {
          return mergeFrom((com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto other) {
        if (other == com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto.getDefaultInstance()) return this;
        if (!other.getAuthorizationUri().isEmpty()) {
          authorizationUri_ = other.authorizationUri_;
          onChanged();
        }
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getRedirectUri().isEmpty()) {
          redirectUri_ = other.redirectUri_;
          onChanged();
        }
        if (!other.scopes_.isEmpty()) {
          if (scopes_.isEmpty()) {
            scopes_ = other.scopes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureScopesIsMutable();
            scopes_.addAll(other.scopes_);
          }
          onChanged();
        }
        if (!other.getState().isEmpty()) {
          state_ = other.state_;
          onChanged();
        }
        internalGetMutableAdditionalParameters().mergeFrom(
            other.internalGetAdditionalParameters());
        if (!other.getAuthorizationRequestUri().isEmpty()) {
          authorizationRequestUri_ = other.authorizationRequestUri_;
          onChanged();
        }
        internalGetMutableAttributes().mergeFrom(
            other.internalGetAttributes());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object authorizationUri_ = "";
      /**
       * <code>string authorizationUri = 1;</code>
       * @return The authorizationUri.
       */
      public java.lang.String getAuthorizationUri() {
        java.lang.Object ref = authorizationUri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authorizationUri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string authorizationUri = 1;</code>
       * @return The bytes for authorizationUri.
       */
      public com.google.protobuf.ByteString
          getAuthorizationUriBytes() {
        java.lang.Object ref = authorizationUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authorizationUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string authorizationUri = 1;</code>
       * @param value The authorizationUri to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorizationUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authorizationUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string authorizationUri = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorizationUri() {
        
        authorizationUri_ = getDefaultInstance().getAuthorizationUri();
        onChanged();
        return this;
      }
      /**
       * <code>string authorizationUri = 1;</code>
       * @param value The bytes for authorizationUri to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorizationUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authorizationUri_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientId_ = "";
      /**
       * <code>string clientId = 2;</code>
       * @return The clientId.
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clientId = 2;</code>
       * @return The bytes for clientId.
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientId = 2;</code>
       * @param value The clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string clientId = 2;</code>
       * @param value The bytes for clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object redirectUri_ = "";
      /**
       * <code>string redirectUri = 3;</code>
       * @return The redirectUri.
       */
      public java.lang.String getRedirectUri() {
        java.lang.Object ref = redirectUri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          redirectUri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string redirectUri = 3;</code>
       * @return The bytes for redirectUri.
       */
      public com.google.protobuf.ByteString
          getRedirectUriBytes() {
        java.lang.Object ref = redirectUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          redirectUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string redirectUri = 3;</code>
       * @param value The redirectUri to set.
       * @return This builder for chaining.
       */
      public Builder setRedirectUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        redirectUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string redirectUri = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRedirectUri() {
        
        redirectUri_ = getDefaultInstance().getRedirectUri();
        onChanged();
        return this;
      }
      /**
       * <code>string redirectUri = 3;</code>
       * @param value The bytes for redirectUri to set.
       * @return This builder for chaining.
       */
      public Builder setRedirectUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        redirectUri_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList scopes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureScopesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          scopes_ = new com.google.protobuf.LazyStringArrayList(scopes_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string scopes = 4;</code>
       * @return A list containing the scopes.
       */
      public com.google.protobuf.ProtocolStringList
          getScopesList() {
        return scopes_.getUnmodifiableView();
      }
      /**
       * <code>repeated string scopes = 4;</code>
       * @return The count of scopes.
       */
      public int getScopesCount() {
        return scopes_.size();
      }
      /**
       * <code>repeated string scopes = 4;</code>
       * @param index The index of the element to return.
       * @return The scopes at the given index.
       */
      public java.lang.String getScopes(int index) {
        return scopes_.get(index);
      }
      /**
       * <code>repeated string scopes = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the scopes at the given index.
       */
      public com.google.protobuf.ByteString
          getScopesBytes(int index) {
        return scopes_.getByteString(index);
      }
      /**
       * <code>repeated string scopes = 4;</code>
       * @param index The index to set the value at.
       * @param value The scopes to set.
       * @return This builder for chaining.
       */
      public Builder setScopes(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureScopesIsMutable();
        scopes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string scopes = 4;</code>
       * @param value The scopes to add.
       * @return This builder for chaining.
       */
      public Builder addScopes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureScopesIsMutable();
        scopes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string scopes = 4;</code>
       * @param values The scopes to add.
       * @return This builder for chaining.
       */
      public Builder addAllScopes(
          java.lang.Iterable<java.lang.String> values) {
        ensureScopesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, scopes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string scopes = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearScopes() {
        scopes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string scopes = 4;</code>
       * @param value The bytes of the scopes to add.
       * @return This builder for chaining.
       */
      public Builder addScopesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureScopesIsMutable();
        scopes_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object state_ = "";
      /**
       * <code>string state = 5;</code>
       * @return The state.
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string state = 5;</code>
       * @return The bytes for state.
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string state = 5;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string state = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>string state = 5;</code>
       * @param value The bytes for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        state_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> additionalParameters_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAdditionalParameters() {
        if (additionalParameters_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AdditionalParametersDefaultEntryHolder.defaultEntry);
        }
        return additionalParameters_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableAdditionalParameters() {
        onChanged();;
        if (additionalParameters_ == null) {
          additionalParameters_ = com.google.protobuf.MapField.newMapField(
              AdditionalParametersDefaultEntryHolder.defaultEntry);
        }
        if (!additionalParameters_.isMutable()) {
          additionalParameters_ = additionalParameters_.copy();
        }
        return additionalParameters_;
      }

      public int getAdditionalParametersCount() {
        return internalGetAdditionalParameters().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
       */

      @java.lang.Override
      public boolean containsAdditionalParameters(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAdditionalParameters().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAdditionalParametersMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAdditionalParameters() {
        return getAdditionalParametersMap();
      }
      /**
       * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getAdditionalParametersMap() {
        return internalGetAdditionalParameters().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
       */
      @java.lang.Override

      public java.lang.String getAdditionalParametersOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAdditionalParameters().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
       */
      @java.lang.Override

      public java.lang.String getAdditionalParametersOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAdditionalParameters().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAdditionalParameters() {
        internalGetMutableAdditionalParameters().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
       */

      public Builder removeAdditionalParameters(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAdditionalParameters().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableAdditionalParameters() {
        return internalGetMutableAdditionalParameters().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
       */
      public Builder putAdditionalParameters(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAdditionalParameters().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; additionalParameters = 6;</code>
       */

      public Builder putAllAdditionalParameters(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAdditionalParameters().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.lang.Object authorizationRequestUri_ = "";
      /**
       * <code>string authorizationRequestUri = 7;</code>
       * @return The authorizationRequestUri.
       */
      public java.lang.String getAuthorizationRequestUri() {
        java.lang.Object ref = authorizationRequestUri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authorizationRequestUri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string authorizationRequestUri = 7;</code>
       * @return The bytes for authorizationRequestUri.
       */
      public com.google.protobuf.ByteString
          getAuthorizationRequestUriBytes() {
        java.lang.Object ref = authorizationRequestUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authorizationRequestUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string authorizationRequestUri = 7;</code>
       * @param value The authorizationRequestUri to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorizationRequestUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authorizationRequestUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string authorizationRequestUri = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorizationRequestUri() {
        
        authorizationRequestUri_ = getDefaultInstance().getAuthorizationRequestUri();
        onChanged();
        return this;
      }
      /**
       * <code>string authorizationRequestUri = 7;</code>
       * @param value The bytes for authorizationRequestUri to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorizationRequestUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authorizationRequestUri_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> attributes_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAttributes() {
        if (attributes_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AttributesDefaultEntryHolder.defaultEntry);
        }
        return attributes_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableAttributes() {
        onChanged();;
        if (attributes_ == null) {
          attributes_ = com.google.protobuf.MapField.newMapField(
              AttributesDefaultEntryHolder.defaultEntry);
        }
        if (!attributes_.isMutable()) {
          attributes_ = attributes_.copy();
        }
        return attributes_;
      }

      public int getAttributesCount() {
        return internalGetAttributes().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 8;</code>
       */

      @java.lang.Override
      public boolean containsAttributes(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAttributes().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAttributesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
        return getAttributesMap();
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 8;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
        return internalGetAttributes().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 8;</code>
       */
      @java.lang.Override

      public java.lang.String getAttributesOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttributes().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 8;</code>
       */
      @java.lang.Override

      public java.lang.String getAttributesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttributes().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAttributes() {
        internalGetMutableAttributes().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 8;</code>
       */

      public Builder removeAttributes(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAttributes().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableAttributes() {
        return internalGetMutableAttributes().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 8;</code>
       */
      public Builder putAttributes(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAttributes().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 8;</code>
       */

      public Builder putAllAttributes(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAttributes().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequestDto)
    }

    // @@protoc_insertion_point(class_scope:com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequestDto)
    private static final com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto();
    }

    public static com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OAuth2AuthorizationRequestDto>
        PARSER = new com.google.protobuf.AbstractParser<OAuth2AuthorizationRequestDto>() {
      @java.lang.Override
      public OAuth2AuthorizationRequestDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OAuth2AuthorizationRequestDto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OAuth2AuthorizationRequestDto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OAuth2AuthorizationRequestDto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.icthh.xm.gate.security.oauth2.dto.OAuth2AuthorizationRequest.OAuth2AuthorizationRequestDto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_AdditionalParametersEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_AdditionalParametersEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_AttributesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_AttributesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nYhome/ssenko/work/xm-gate/src/main/reso" +
      "urces/config/proto/OAuth2AuthorizationRe" +
      "quest.proto\022%com.icthh.xm.gate.security." +
      "oauth2.dto\"\370\003\n\035OAuth2AuthorizationReques" +
      "tDto\022\030\n\020authorizationUri\030\001 \001(\t\022\020\n\010client" +
      "Id\030\002 \001(\t\022\023\n\013redirectUri\030\003 \001(\t\022\016\n\006scopes\030" +
      "\004 \003(\t\022\r\n\005state\030\005 \001(\t\022|\n\024additionalParame" +
      "ters\030\006 \003(\0132^.com.icthh.xm.gate.security." +
      "oauth2.dto.OAuth2AuthorizationRequestDto" +
      ".AdditionalParametersEntry\022\037\n\027authorizat" +
      "ionRequestUri\030\007 \001(\t\022h\n\nattributes\030\010 \003(\0132" +
      "T.com.icthh.xm.gate.security.oauth2.dto." +
      "OAuth2AuthorizationRequestDto.Attributes" +
      "Entry\032;\n\031AdditionalParametersEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\0321\n\017Attributes" +
      "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_descriptor,
        new java.lang.String[] { "AuthorizationUri", "ClientId", "RedirectUri", "Scopes", "State", "AdditionalParameters", "AuthorizationRequestUri", "Attributes", });
    internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_AdditionalParametersEntry_descriptor =
      internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_descriptor.getNestedTypes().get(0);
    internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_AdditionalParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_AdditionalParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_AttributesEntry_descriptor =
      internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_descriptor.getNestedTypes().get(1);
    internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_icthh_xm_gate_security_oauth2_dto_OAuth2AuthorizationRequestDto_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
